### ISSUE TITLE
RuntimeError when running train.py

### ISSUE THREAD

**Issue by Zpadger** [layumi/Person_reID_baseline_pytorch#128]
Hello,I try to run the train.py on my Windows,but there is a RuntimeError when running it:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\Anaconda3\envs\pytorch_gpu\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\runpy.py", line 85, in _run_code
Traceback (most recent call last):
  File "E:/PycharmProjects/PyTorch/train.py", line 139, in <module>
    exec(code, run_globals)
  File "E:\PycharmProjects\PyTorch\train.py", line 139, in <module>
    inputs, classes = next(iter(dataloaders['train']))
  File "D:\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    inputs, classes = next(iter(dataloaders['train']))
  File "D:\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    return _DataLoaderIter(self)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\process.py", line 112, in start
    w.start()
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\context.py", line 223, in _Popen
    self._popen = self._Popen(self)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\context.py", line 322, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    return Popen(process_obj)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\reduction.py", line 60, in dump
    _check_not_importing_main()
  File "D:\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
    is not going to be frozen to produce an executable.''')
 An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Could you help me how to solve it?Thx~

**Comment by layumi** [comment]
windows pytorch seems to have some issues with `nworkers`

Would you like to try change `nworkers=0` in train.py? It might be helpful.

**Comment by yunhyuck** [comment]
Thank you for your comment. I Clear !
