### ISSUE TITLE
Error about visual_heatmap.py

### ISSUE THREAD

**Issue by Tiemei889** [layumi/Person_reID_baseline_pytorch#168]
torch.Size([32, 1024, 16, 8])
(1024, 16, 8)
Traceback (most recent call last):
  File "visual_heatmap.py", line 91, in <module>
    heatmap2d(imgpath[0][0],heatmap)
  File "visual_heatmap.py", line 54, in heatmap2d
    heatmap = ax1.imshow(arr, cmap='viridis')
  File "/home/baller/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/home/baller/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 5501, in imshow
    im.set_data(X)
  File "/home/baller/anaconda3/lib/python3.7/site-packages/matplotlib/image.py", line 654, in set_data
    raise TypeError("Invalid dimensions for image data")
TypeError: Invalid dimensions for image data

运行visual_heatmap.py一直说图片维度错误，请问一下这个怎么解决

**Comment by layumi** [comment]
It looks like the channel number error. For image visualization, you should make sure that the final output is 3-channel or 1-channel.
