### ISSUE TITLE
How to read camera ID for VIPeR dataset

### ISSUE THREAD

**Issue by MAdil45** [layumi/Person_reID_baseline_pytorch#170]
Hi @layumi  I am sorry to disturb you.I have successfully trained the model on VIPeR dataset but due to camera ID issue i cannot figure it out how to read camera ID for during testing. This guy developed Dataset by using camera a & b. Can you please help me out and  point me in the right direction. I will really appreciate it. 
Thanks in advance. Hoping to get positive response.

**Comment by layumi** [comment]
Hi @MAdil45 
You may simply set the images from A as Cam 1, and the images from B as Cam 2.

**Comment by MAdil45** [comment]
@layumi Thank you so much for your positive response. I did what you told me to but still i am unable to read the camera id. Can you please help me out of it. I am new in this field and i am trying my best to learn. 
I am getting following error. I do not know how to edit this part of the code so that it can read camera id correctly. My code is like this.
filename = os.path.basename(path)
        label = filename[0:4]
        camera = filename.split('c')[1]
        if label[0:2]=='-1':
            labels.append(-1)
        else:
            labels.append(int(label))
        camera_id.append(int(camera[0]))
    return camera_id, labels
Images name looks like this:
c2_002_90.png

I am getting following error.

config = yaml.load(stream)
We use the scale: 1
Traceback (most recent call last):
  File "test.py", line 203, in <module>
    gallery_cam,gallery_label = get_id(gallery_path)
  File "test.py", line 196, in get_id
    labels.append(int(label))
ValueError: invalid literal for int() with base 10: 'c2_0'

**Comment by MAdil45** [comment]
@layumi Hey Brother. Sorry to disturb you. I am still waiting for your positive response. I will really appreciate it. Thanks in advance.

**Comment by layumi** [comment]
I think that the correct final name is '002_c2_90.png' or something like that.

**Comment by MAdil45** [comment]
@layumi Thankyou so much Brother for your positive response. Appreciate it. However, i changed my code according to the above suggestion and now i am getting following error. I tried different ways but i couldn't able solve it. Kindly have a look. Thanks in advance. 
We use the scale: 1
Traceback (most recent call last):
  File "test.py", line 203, in <module>
    gallery_cam,gallery_label = get_id(gallery_path)
  File "test.py", line 197, in get_id
    camera_id.append(int(camera[0]))
IndexError: string index out of range

**Comment by layumi** [comment]
Could you print the `camera` to see which one cause the error?

**Comment by Dipeshtamboli** [comment]
I am not able to download the VIPeR dataset. It is showing that the VIPeR dataset link is directing to a page which is removed. I tried downloading it from the site directly but I don't have access to it. Can you please tell me how can I do that?
