### ISSUE TITLE
a error in train.py

### ISSUE THREAD

**Issue by hujiaodou96** [layumi/Person_reID_baseline_pytorch#18]
python train.py --gpu_ids 0 --name ft_ResNet50 --train_all --batchsize 32
 error occurs as below:

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\pytorch\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\pytorch\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by layumi** [comment]
Hi @hujiaodou96 ,
It seems to be an error occurred in Windows pytorch.
You may check https://github.com/pytorch/pytorch/issues/5858

**Comment by hujiaodou96** [comment]
thanks! I add this sentence and a main function  ,but it continues with another error as:

Traceback (most recent call last):
  File "train.py", line 287, in <module>
    main()
  File "train.py", line 262, in main
    ], momentum=0.9, weight_decay=5e-4, nesterov=True)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\pytorch\lib\site-packages\torch\optim\sgd.py", line 53, in __init__
    if not 0.0 <= lr:
TypeError: unorderable types: float() <= object()

how to solve this ...

**Comment by layumi** [comment]
Sorry @hujiaodou96, 
Would you like to run the code on Ubuntu?

**Comment by yzy1996** [comment]
I met the same problem on Windows. I will try again on Ubantu

**Comment by Mr-zhu0912** [comment]
@hujiaodou96 Hi, i also meet this question, could you show me what you add in sourcecode?my mailbox is 2941746806@qq.com.Thank you a lot!

**Comment by hujiaodou96** [comment]
do you mean the 'main' problem or that of 'the learning rate'? for the former I add a main function  ,and for the latter I use a constant learning rate in windows pytorch ,and in Linux system ,this code works well .

**Comment by Mr-zhu0912** [comment]
@hujiaodou96 it's "main" problem. I want to know  the specific method you add main function in detail. Can you send me your source code in windows if it is convenient?think you !

**Comment by vyshnavi-hue** [comment]
Hi,I am using object detection using pytorch in windows
even i am getting same error as below:

is not going to be frozen to produce an executable.''')
**RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                torch.multiprocessing.freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe**


can you tell where i need to keep this code:


**def run():
    torch.multiprocessing.freeze_support()
    print('loop')

if __name__ == '__main__':
    run()**

can you please help me ASAP?

**Comment by layumi** [comment]
@vyshnavi-hue 
I guess that you need to set nworkers=0. (which is in Dataloader)

**Comment by vyshnavi-hue** [comment]
yeah i checked in Dataloader ,already nworkers=0 and still its not working.can you give any other solution.Thanks in Advance

**Comment by layumi** [comment]
Please check with the Pytorch Windows for more reference.
- https://github.com/pytorch/pytorch/issues/5858
- https://pytorch.org/docs/stable/multiprocessing.html
- https://github.com/pytorch/pytorch/issues/7485
