### ISSUE TITLE
test.py OOM(batchsize doesn't work)

### ISSUE THREAD

**Issue by Cai72** [layumi/Person_reID_baseline_pytorch#194]
I run test.py with "--fp16 --PCB" and "--batchsize" of 8/16/32/64.
Change of batchsize doesn't work for me.
The gpu is GeForce GTX1080.
The train.py works well.
`-------test-----------
Traceback (most recent call last):

  File "test.py", line 249, in <module>

    gallery_feature = extract_feature(model,dataloaders['gallery'])

  File "test.py", line 169, in extract_feature

    outputs = model(input_img) 

  ···

  ··· (My code traceback here.)

  ···

RuntimeError: CUDA out of memory. Tried to allocate 4.50 GiB (GPU 0; 10.92 GiB total capacity; 1.74 GiB already allocated; 3.88 GiB free; 4.00 GiB cached)
`
I wonder if there is a possible way to run my code.

**Comment by Cai72** [comment]
I found bugs in my own runscript code which doesn't assign the batchsize correctly.After fix it, it works.
