### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by phil-zd** [layumi/Person_reID_baseline_pytorch#214]
python train.py --gpu_ids 0 --name ft_ResNet50 --train_all --batchsize 32  --data_dir your_data_path
[Resize(size=(256, 128), interpolation=PIL.Image.BICUBIC), Pad(padding=10, fill=0, padding_mode=constant), RandomCrop(size=(256, 128), padding=None), RandomHorizontalFlip(p=0.5), ToTensor(), Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])]
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    data_transforms['train'])
  File "/home/zhuda/anaconda3/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 206, in __init__
    is_valid_file=is_valid_file)
  File "/home/zhuda/anaconda3/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 94, in __init__
    classes, class_to_idx = self._find_classes(self.root)
  File "/home/zhuda/anaconda3/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 121, in _find_classes
    classes = [d.name for d in os.scandir(dir) if d.is_dir()]
FileNotFoundError: [Errno 2] No such file or directory: 'your_data_path/train_all'

**Comment by layumi** [comment]
Could you check the dataset path? Is it correct?

**Comment by phil-zd** [comment]
Ok，Thanks.

**Comment by phil-zd** [comment]
Thanks again, I mistakenly thought that I only need to use the train folder
