### ISSUE TITLE
ModuleNotFoundError: No module named 'model'

### ISSUE THREAD

**Issue by atul2oct** [layumi/Person_reID_baseline_pytorch#243]
Hello
You have done excellent and impressive work. Actually, I am new in machine learning and I was trying to run the code but I was facing problems. It would be grateful if you help me
i haven't changed the code except  parser.add_argument('--data_dir',default='./Market/pytorch/',type=str, help='training dir path')
i have downloaded the model folder from https://drive.google.com/file/d/1XVEYb0TN2SbBYOqf8SzazfYZlpH9CxyE/view
but still the same .
model folder dir "C:\Users\ATUL\Desktop\Python\Person_reID_baseline_pytorch-master\model"
and train.py dir "C:\Users\ATUL\Desktop\Python\Person_reID_baseline_pytorch-master"
o/p-
This is not an error. If you want to use low precision, i.e., fp16, please install the apex with cuda support (https://github.com/NVIDIA/apex) and update pytorch to 1.0
[Resize(size=(256, 128), interpolation=PIL.Image.BICUBIC), Pad(padding=10, fill=0, padding_mode=constant), RandomCrop(size=(256, 128), padding=None), RandomHorizontalFlip(p=0.5), ToTensor(), Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])]

Traceback (most recent call last):
File "", line 1, in
File "C:\Users\ATUL\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
exitcode = _main(fd, parent_sentinel)
File "C:\Users\ATUL\Anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
prepare(preparation_data)
File "C:\Users\ATUL\Anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
_fixup_main_from_path(data['init_main_from_path'])
File "C:\Users\ATUL\Anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
main_content = runpy.run_path(main_path,
File "C:\Users\ATUL\Anaconda3\lib\runpy.py", line 265, in run_path
return _run_module_code(code, init_globals, run_name,
File "C:\Users\ATUL\Anaconda3\lib\runpy.py", line 97, in _run_module_code
_run_code(code, mod_globals, init_globals,
File "C:\Users\ATUL\Anaconda3\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\ATUL\Desktop\Python\Person_reID_baseline_pytorch-master\train.py", line 19, in
from model import ft_net, ft_net_dense, ft_net_NAS, PCB
ModuleNotFoundError: No module named 'model'

**Comment by layumi** [comment]
Do you move the baseline folder?

model  is to call `model.py` in this repo. 

I am not sure whether there are any differences on WIndows. It would be better to run on Ubuntu.
