### ISSUE TITLE
environment?

### ISSUE THREAD

**Issue by sopsos** [layumi/Person_reID_baseline_pytorch#249]
Can you provide at least one exact set of dependencies that work for you? I am trying to just run testing with a pretrained model and I get the following error:

```
$ python test.py --test_dir Market-1501-v15.09.15/pytorch
This is not an error. If you want to use low precision, i.e., fp16, please install the apex with cuda support (https://github.com/NVIDIA/apex) and update pytorch to 1.0
test.py:48: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(stream)
We use the scale: 1
-------test-----------
256
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1544174967633/work/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
Traceback (most recent call last):
  File "test.py", line 248, in <module>
    gallery_feature = extract_feature(model,dataloaders['gallery'])
  File "test.py", line 168, in extract_feature
    outputs = model(input_img) 
  File "/home/me/.conda/envs/person-reid-baseline-pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/code/Person_reID_baseline_pytorch/model.py", line 79, in forward
    x = self.model.conv1(x)
  File "/home/me/.conda/envs/person-reid-baseline-pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/.conda/envs/person-reid-baseline-pytorch/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1544174967633/work/aten/src/THC/THCGeneral.cpp:405
```

This happens regardless of the model I set in `--name`.
Here's my dependencies as a conda environment
```
name: person-reid-baseline-pytorch
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.12.8=h06a4308_0
  - certifi=2020.12.5=py36h06a4308_0
  - cffi=1.14.4=py36h261ae71_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - freetype=2.10.4=h5ab3b9f_0
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=heb0550a_3
  - mkl=2018.0.3=1
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py36hff7bd54_0
  - numpy=1.13.1=py36h5bc529a_2
  - olefile=0.46=py36_0
  - openssl=1.1.1i=h27cfd23_0
  - pillow=8.1.0=py36he98fc37_0
  - pip=20.3.3=py36h06a4308_0
  - pycparser=2.20=py_2
  - python=3.6.12=hcff3b4d_2
  - pytorch=1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1
  - pyyaml=5.3.1=py36h7b6447c_1
  - readline=8.0=h7b6447c_0
  - scipy=1.1.0=py36hd20e5f9_0
  - setuptools=51.0.0=py36h06a4308_2
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.2.1=py_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - munch==2.5.0
    - pretrainedmodels==0.7.4
    - tqdm==4.55.1
```

**Comment by sopsos** [comment]
Figured it out. CUDA 9.0 fixes it, but it needs to be installed before everything else. This installed the appropriate dependencies:
```
conda install python=3.6 numpy=1.13.1 pytorch=1.0 torchvision=0.2.1 cudatoolkit=9.0 scipy pyyaml -c pytorch
pip install pretrainedmodels
```
