### ISSUE TITLE
Error when using PCB

### ISSUE THREAD

**Issue by YHangbin** [layumi/Person_reID_baseline_pytorch#27]
Hi, @layumi.Thanks for the great code. I meet some problems when using the PCB.
`python train.py --PCB --batchsize 10--name PCB-10`. only change the `batchsize` to 10, When using PCB to train,  It report as below:
```
Traceback (most recent call last):
  File "train.py", line 273, in <module>
    model = PCB(len(class_names))
  File "/home/yhangbin/code/github/Person_reID_baseline_pytorch/model.py", line 140, in __init__
    setattr(self, name, ClassBlock(2048, class_num, True, False, 256))
TypeError: __init__() takes from 3 to 4 positional arguments but 6 were given
```
I changed  `ClassBlock(2048, class_num, True, False, 256)` to ` ClassBlock(2048, class_num,  256)`  this error was solved. But when  training at epoch 1 , I got such errors as below in the val phase
```
train Loss: 3.7999 Acc: 0.0192
Traceback (most recent call last):
  File "train.py", line 332, in <module>
    model = train_model(model, criterion, optimizer_ft, exp_lr_scheduler,num_epochs=10)
  File "train.py", line 176, in train_model
    outputs = model(inputs)
  File "/home/yhangbin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yhangbin/code/github/Person_reID_baseline_pytorch/model.py", line 162, in forward
    predict[i] = c(part[i])
  File "/home/yhangbin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yhangbin/code/github/Person_reID_baseline_pytorch/model.py", line 47, in forward
    x = self.add_block(x)
  File "/home/yhangbin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yhangbin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/yhangbin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yhangbin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 37, in forward
    self.training, self.momentum, self.eps)
  File "/home/yhangbin/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1013, in batch_norm
    return f(input, weight, bias)
RuntimeError: CHECK_ARG(tensor->nDimension >= 2 && tensor->nDimension <= 5) failed at torch/csrc/cudnn/BatchNorm.cpp:13
```
I don't know how to solve this problem，thanks for your help.

**Comment by layumi** [comment]
Hi @YHangbin, 

Sorry. I forgot to update the ClassBlock. Now I add the two options. You may take a look at https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/model.py#L29

 Does the second problem still appear?

**Comment by YHangbin** [comment]
I really appreciate your help, I found that the second problem was not caused by the ClassBlock but caused by the setting of `batchsize` . I changed `--batchsize 10-` to `--batchsize 16` it works very well.Thank you for your help again.

**Comment by layumi** [comment]
Thank you @YHangbin . 
For the second question, I think it may be due to the batchsize=1 (in the last iteration).
Batchnorm do not accept the batchsize=1.
https://github.com/pytorch/pytorch/issues/4534

**Comment by YHangbin** [comment]
Hi @layumi ,
Thank you for reminding, maybe it's the reason.
