### ISSUE TITLE
使用swin时训练错误

### ISSUE THREAD

**Issue by LazyHQ** [layumi/Person_reID_baseline_pytorch#291]
**Describe the bug**
使用swin时，提示Traceback (most recent call last):
  File "train.py", line 386, in <module>
    model = ft_net_swin(len(class_names), opt.droprate, opt.stride, circle =opt.circle)
  File "/home/mist/Person_reID_baseline_pytorch/model.py", line 103, in __init__
    model_ft = timm.create_model('swin_base_patch4_window7_224', pretrained=True)
  File "/mistgpu/miniconda/envs/swin/lib/python3.7/site-packages/timm/models/factory.py", line 59, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (swin_base_patch4_window7_224)

不使用swin时可以正常训练，不知道问题出在哪里。

**Comment by layumi** [comment]
What's the version of your `timm`?

**Comment by LazyHQ** [comment]
0.3.2

timm              0.3.2
torch             1.7.1
torchaudio        0.7.0a0+a853dff
torchvision       0.8.2

**Comment by LazyHQ** [comment]
> 你的是什么版本`timm`？

0.3.2

**Comment by layumi** [comment]
My version is '0.4.13' 
Please update the time

**Comment by LazyHQ** [comment]
> My version is '0.4.13' Please update the time

Thank you, the problem is solved
