### ISSUE TITLE
Error when trying to test a Swin trained model

### ISSUE THREAD

**Issue by paterique** [layumi/Person_reID_baseline_pytorch#293]
Hi there, I am erroring after training my dataset with Swin instead of ResNet50. I get the following error

Traceback (most recent call last):
  File "test.py", line 226, in <module>
    model = load_network(model_structure)
  File "test.py", line 132, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ft_net:
	Missing key(s) in state_dict: "model.conv1.weight", "model.bn1.weight", "model.bn1.bias", "model.bn1.running_mean", "model.bn1.running_var", "model.layer1.0.conv1.weight", "model.layer1.0.bn1.weight", "model.layer1.0.bn1.bias", "model.layer1.0.bn1.running_mean", "model.layer1.0.bn1.running_var", "model.layer1.0.conv2.weight", "model.layer1.0.bn2.weight", "model.layer1.0.bn2.bias", "model.layer1.0.bn2.running_mean", "model.layer1.0.bn2.running_var", .........................(this goes on for like 50 lines so i thought id cut it off)

Any hints or tips for what I am doing wrong? I've tried looking into it but can't figure it out. Thanks :)

**Comment by paterique** [comment]
For some reason my train file was updated for swin use but my test wasn't, fixed :)
