### ISSUE TITLE
我修改模型后训练无报错，测试报错

### ISSUE THREAD

**Issue by mcjqwer** [layumi/Person_reID_baseline_pytorch#295]
**Describe the bug**
数据集任然是market1501，我改成了resnet34主干，输出维度是512，网络的class类别数目也都改了
以下是报错内容
This is not an error. If you want to use low precision, i.e., fp16, please install the apex with cuda support (https://github.com/NVIDIA/apex) and update pytorch to 1.0
test.py:47: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(stream)
config the yaml: 751
res50
We use the scale: 1
-------test-----------
类别数目: 751
Traceback (most recent call last):
  File "test.py", line 265, in <module>
    gallery_feature = extract_feature(model,dataloaders['gallery'])
  File "test.py", line 183, in extract_feature
    ff += outputs
RuntimeError: The size of tensor a (512) must match the size of tensor b (751) at non-singleton dimension 1

直接用原来的resnet50就没事的。
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mcjqwer** [comment]
弄好了 应该是我的模型和你的模型的classifier层有区别 换你的分类层就没事了....
