### ISSUE TITLE
更换模型训练出错

### ISSUE THREAD

**Issue by gubei528** [layumi/Person_reID_baseline_pytorch#315]
学长，您好，我想将resnet50替换成resnet18，但是在训练的时候，出现了  
Traceback (most recent call last):
  File "D:/Master/Person_reID_baseline_pytorch/train.py", line 465, in <module>
    num_epochs=60)
  File "D:/Master/Person_reID_baseline_pytorch/train.py", line 236, in train_model
    outputs = model(inputs)
  File "D:\Anaconda\Anaconda\envs\deepsort\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Master\Person_reID_baseline_pytorch\model.py", line 96, in forward
    x = self.classifier(x)
  File "D:\Anaconda\Anaconda\envs\deepsort\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Master\Person_reID_baseline_pytorch\model.py", line 57, in forward
    x = self.add_block(x)
  File "D:\Anaconda\Anaconda\envs\deepsort\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\Anaconda\envs\deepsort\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "D:\Anaconda\Anaconda\envs\deepsort\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\Anaconda\envs\deepsort\lib\site-packages\torch\nn\modules\linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\Anaconda\Anaconda\envs\deepsort\lib\site-packages\torch\nn\functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 dim 1 must match mat2 dim 0

进程已结束，退出代码为 1

这个错误，请问这是哪里出问题了呢

**Comment by gubei528** [comment]
学长，我解决了这个问题，您设置的新的分类层的输入要跟resnet的输出相对应，对于resnet18，他的最后输出是512维。因此在全连接层要将输入变成512！
