### ISSUE TITLE
Can't find PCB_test and other pre-trained models in Goodle drive

### ISSUE THREAD

**Issue by GayatriPurandharT** [layumi/Person_reID_baseline_pytorch#318]
Hi @layumi, thanks for the timely updates to this repo, it's really helpful.
After the load model step, there's the removal of the final FC layer step :
```
if opt.PCB:
    #if opt.fp16:
    #    model = PCB_test(model[1])
    #else:
    **model = PCB_test(model)**
else:
    #if opt.fp16:
        #model[1].model.fc = nn.Sequential()
        #model[1].classifier = nn.Sequential()
    #else:
    model.classifier.classifier = nn.Sequential()
```
I couldn't find any PCB_test model from the drive, and when I use just PCB, I have an error:

```
Traceback (most recent call last):
  File "test_PCB.py", line 259, in <module>
    model = PCB(model)
  File "/content/gdrive/MyDrive/cropAndHri_engine/model.py", line 178, in __init__
    setattr(self, name, ClassBlock(2048, class_num, droprate=0.5, relu=False, bnorm=True, num_bottleneck=256))
  File "/content/gdrive/MyDrive/cropAndHri_engine/model.py", line 48, in __init__
    classifier += [nn.Linear(num_bottleneck, class_num)]
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py", line 72, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: new() received an invalid combination of arguments - got (PCB, int), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (PCB, int)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (PCB, int)
```

Please point to any mistake I could be committing here. Thanks very much.

**Comment by layumi** [comment]
Hi @GayatriPurandharT  
Recently I update models, so some test models are missing. 
It would be good if you could re-train the model by yourself. Actually, it usually only takes one hour to get the final model. 

Thanks a lot for your attention on our repo.

**Comment by GayatriPurandharT** [comment]
Thanks for your response @layumi.
I'd do that for PCB, however, you mentioned that models like Swin would require huge GPU resources, it'd be really helpful if you could upload those (cuz I don't have access to high-end resources at his point).
Thanks a lot.
