### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'Tensor' and 'list'

### ISSUE THREAD

**Issue by starstarb** [layumi/Person_reID_baseline_pytorch#320]
test.py --use_swin
  warnings.warn(
-------test-----------
128
Traceback (most recent call last):
  File "/root/autodl-tmp/testBest.py", line 317, in <module>
    gallery_feature = extract_feature(model, dataloaders['gallery'])
  File "/root/autodl-tmp/testBest.py", line 224, in extract_feature
    ff += outputs
TypeError: unsupported operand type(s) for +=: 'Tensor' and 'list'

郑老师您好，我使用您的代码训练swin，预测时，复制您的测试代码运行，报了这个错，有没有什么办法解决，google了半天也没解决，感谢指导

**Comment by layumi** [comment]
Hi @starstarb 

这一步是用来 叠 原始图像特征 和 fliplr以后图像特征的。
看上去是你类型出了问题 

我不确定是不是 你原始code里也有叫outputs 或者 ff的？

**Comment by starstarb** [comment]
郑老师，没有修改过您的transformer模型，我最近重新训练了一遍您的模型swin Transformer脚本，训练模型没有问题，测试的时候还是报这个错误，训练脚本和测试脚本也没有作修改，可是依然报这个错误，调试了很久还是没有结果。
问题：
Traceback (most recent call last):
  File "test.py", line 325, in <module>
    gallery_feature = extract_feature(model, dataloaders['gallery'])
  File "test.py", line 227, in extract_feature
ff += outputs
TypeError: unsupported operand type(s) for +=: 'Tensor' and 'list'

首先调试发现：ff为tensor类型，outputs为List类型
做过的尝试：
1.outputs = torch.tensor([item.cpu().detach().numpy() for item in outputs]).cuda()
变换outputs类型为tensor张量，outputs张量的形状是torch.Size([2, 32, 512])， ff张量的形状是torch.Size([32, 512])，报这个错误RuntimeError: output with shape [32, 512] doesn't match the broadcast shape [2, 32, 512]，两tensor形状不匹配
2.设置outputs = outputs.reshape([32,512])，报这个错误RuntimeError: shape '[32, 512]' is invalid for input of size 32768
3. outputs = torch.squeeze(outputs, dim = 0) 对outpus降维度 报：RuntimeError: output with shape [32, 512] doesn't match the broadcast shape [2, 32, 512] 发现降维失败，该行代码不起作用，没有降维
4. ff = ff.unsqueeze(0) 对ff升维度，报：RuntimeError: output with shape [1, 32, 512] doesn't match the broadcast shape [2, 32, 512] 两个tensor的shape还是不一样
目前测试swin Transformer模型报这个错误，有没有什么办法解决啊，感谢郑老师指导 @layumi

**Comment by starstarb** [comment]
6.              outputs = outputs[0]
                outputs.unsqueeze(dim = 0)
我再次对outpus进行降维，然后升维，意思是取第一个维度进行测试，代码能跑通，但是
Rank@1:0.936234 Rank@5:0.971990 Rank@10:0.985101 mAP:0.694360 精度比Resnet提升了3个点，感觉还是有问题

**Comment by starstarb** [comment]
7.                #------------------------------------------------------------------------------
                outputs = torch.tensor([item.cpu().detach().numpy() for item in outputs]).cuda()
                outputs = outputs[1]
                outputs.unsqueeze(dim = 0)
第二个维度测试，精度依然一样，Rank@1:0.936234 Rank@5:0.971990 Rank@10:0.985101 mAP:0.694360
比您提出的低了10个点，我训练时仅修改了batchsize = 100，感觉还是有问题

**Comment by layumi** [comment]
@starstarb 
你好 batch size 太大 会影响结果。 最好还是用。32 或者 16.
