### ISSUE TITLE
使用Swin训练，报错RuntimeError: The size of tensor a (224) must match the size of tensor b (128) at non-singleton dimension 2

### ISSUE THREAD

**Issue by zhangxiaowe** [layumi/Person_reID_baseline_pytorch#337]
**问题描述**
我使用Swin训练，遇到报错RuntimeError: The size of tensor a (224) must match the size of tensor b (128) at non-singleton dimension 2。问题原因好像出在ODFA.py的第68行`transforms.Resize((256,128), interpolation=3),`，但我自己不确定，修改了代码`transforms.Resize((224,224), interpolation=3),`不报错了，但epoch60次的模型测试结果很差。

**我的操作**
1. 源码未改动，v1.0.4和master均出现同样的错误；
2. 运行的命令是`python train.py --use_swin --name swin --batchsize 16`

**报错内容**
```
Epoch 0/59
----------
Traceback (most recent call last):
  File "train.py", line 536, in <module>
    model = train_model(model, criterion, optimizer_ft, exp_lr_scheduler,
  File "train.py", line 275, in train_model
    inputs_adv = ODFA(model, inputs)
  File "/home/REID/Person_reID_baseline_pytorch_2022/Person_reID_baseline_pytorch-1.0.4/ODFA.py", line 45, in ODFA
    inputs = clip(inputs,n)
  File "/home/REID/Person_reID_baseline_pytorch_2022/Person_reID_baseline_pytorch-1.0.4/ODFA.py", line 60, in clip
    inputs[i] = clip_single(inputs[i])
  File "/home/REID/Person_reID_baseline_pytorch_2022/Person_reID_baseline_pytorch-1.0.4/ODFA.py", line 84, in clip_single
    low_mask = input<zeros
RuntimeError: The size of tensor a (224) must match the size of tensor b (128) at non-singleton dimension 2
```

**Screenshots**
![image](https://user-images.githubusercontent.com/77836005/188316528-d7e275cf-cab2-4b8f-9669-b7a4ba260c5b.png)

**Comment by layumi** [comment]
你好。理论上应该不需要改。
因为我写了这一行 https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/train.py#L104 
可能还要check一下 是不是 swin 版本的问题。升级一下 看看？ 

https://github.com/layumi/Person_reID_baseline_pytorch/issues/334

**Comment by layumi** [comment]
Hi @zhangxiaowe 
应该是 新加的 adversarial training 的问题 。 swin还没有适配。所以 导致有点问题。 
我更新了一下。 默认不开启 adv training。

**Comment by zhangxiaowe** [comment]
明白了，问题已解决，非常感谢您的解答，向前辈学习！
