### ISSUE TITLE
ValueError和RuntimeError问题

### ISSUE THREAD

**Issue by chutao-1** [layumi/Person_reID_baseline_pytorch#365]
在运行时出现下面的问题要怎么解决呢？
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/chutao@1/anaconda3/envs/pytorch1.7/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/chutao@1/anaconda3/envs/pytorch1.7/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chutao@1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop
    idx, data = r
ValueError: not enough values to unpack (expected 2, got 0)
Traceback (most recent call last):
  File "train.py", line 540, in <module>
    model = train_model(model, criterion, optimizer_ft, exp_lr_scheduler,
  File "train.py", line 247, in train_model
    for iter, data in enumerate(dataloaders[phase]):
  File "/home/chutao@1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 349, in __iter__
    self._iterator._reset(self)
  File "/home/chutao@1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 852, in _reset
    data = self._get_data()
  File "/home/chutao@1/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1029, in _get_data
    raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: Pin memory thread exited unexpectedly

**Comment by lianshengzhou** [comment]
把train.py的dataloader里的pinmemory改成False

**Comment by layumi** [comment]
感谢。看上去是 pin memory的问题。一般 ubuntu很少遇见不行的。
可能您也需要检查一下pytorch安装。
https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/train.py#L163
