### ISSUE TITLE
Swin在MSMT17测试集的问题

### ISSUE THREAD

**Issue by lianshengzhou** [layumi/Person_reID_baseline_pytorch#367]
您好，想问一下为什么用swinV2在MSMT17测试的时候出现BUG：
RuntimeError: The size of tensor a (4) must match the size of tensor b (32) at non-singleton dimension 1
发现是在这一步出现问题：Traceback (most recent call last):
  File "/content/Person_reID_baseline_pytorch/test.py", line 316, in <module>
    gallery_feature = extract_feature(model,dataloaders['gallery'])
  File "/content/Person_reID_baseline_pytorch/test.py", line 207, in extract_feature
    outputs = model(input_img) 
为什么在Market-1501数据集上不会出现这种BUG呢？

**Comment by chesianatalia** [comment]
Hi, I also have the same issue with a different dataset.
here is the screenshot, I tried months ago and found no problem like this, and suddenly this problem appears. Do you know how to fix it? Thank You

![image](https://user-images.githubusercontent.com/89681954/236667229-09e14ff8-a350-43ab-813d-3071516835ab.png)

**Comment by layumi** [comment]
Hello. It seems like the input size. 
Could you resize the image size as the same one during your training?

**Comment by lianshengzhou** [comment]
但是我在market数据集用Resnet-50、Densennet以及Swin Transformer V2均可以正常运行，在MSMT17数据集上Resnet-50和Densenet均可以正常运行，是两个数据集之间的差异吗？

**Comment by layumi** [comment]
@lianshengzhou 
诶，msmt17应该也是可以的跑的。我怀疑是 input size不对。 您方便的话 可以 print 一下 input size对比一下。

**Comment by chesianatalia** [comment]
Hello, I've checked the input size, and found that the input size was the same during my training and I'm still getting the same error, is there any other solution for this issue? Thank You
the screenshot is attached below:
![image](https://github.com/layumi/Person_reID_baseline_pytorch/assets/89681954/a21a3881-2de4-4347-b53c-4a7c4dc395dd)

this is the input size in my training:
![image](https://github.com/layumi/Person_reID_baseline_pytorch/assets/89681954/f98e157c-c5ae-4b96-b099-4c4ad1efe233)

**Comment by layumi** [comment]
Thank you @chesianatalia 

I will try it and return to you soon.

**Comment by layumi** [comment]
Just for your reference. 
You can check my test MSMT code at https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/test_MSMT.py

**Comment by lianshengzhou** [comment]
@layumi @chesianatalia 试了一下，能够成功运行，结果也很好，感谢及时回复和帮助。

**Comment by chesianatalia** [comment]
Thank you for your explanation, i'll working on it

**Comment by chesianatalia** [comment]
Hi @layumi i've already comment out two lines as you mentioned earlier, turns out there are new error comes up. I've never see an error like this before, and when i undo what i did, the error is still the same, and now it affect on my other model (not only SwinV2). Kindly need your advice

the screenshot attached below:
![image](https://github.com/layumi/Person_reID_baseline_pytorch/assets/89681954/4ef12560-36c8-4936-b571-672db0236e7f)

**Comment by layumi** [comment]
@chesianatalia 

1. Could I know the version of your timm?

2. Could you re-train a new SwinV2 model and test the result?

**Comment by chesianatalia** [comment]
@layumi Hi, I think you are right, I checked another issue, it was due to timm version, I downgraded it, and suddenly it worked, Thank you very much for your suggestion.
Have a great day!

**Comment by layumi** [comment]
Thank you @chesianatalia 

Yes. 

BTW, old timm like 0.6. 0.7 may be not a stable SwinV2. 

For the latest timm, you also need python >=3.8, otherwise you may meet some ``typing'' error.
