### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'prefetch_factor'

### ISSUE THREAD

**Issue by Schanppi** [layumi/Person_reID_baseline_pytorch#371]
This is not an error. If you want to use low precision, i.e., fp16, please install the apex with cuda support (https://github.com/NVIDIA/apex) and update pytorch to 1.0
[Resize(size=(256, 128), interpolation=PIL.Image.BICUBIC), Pad(padding=10, fill=0, padding_mode=constant), RandomCrop(size=(256, 128), padding=None), RandomHorizontalFlip(p=0.5), ToTensor(), Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])]
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    for x in ['train', 'val']}
  File "train.py", line 166, in <dictcomp>
    for x in ['train', 'val']}
TypeError: __init__() got an unexpected keyword argument 'prefetch_factor'

**Comment by layumi** [comment]
Hi @Schanppi 
prefetch_factor is introduced to the latest pytorch (I guess since pytorch 1.6/1.7 or something like that).
