### ISSUE TITLE
Couldn't find any class folder in /content/drive/MyDrive/Person_reID_baseline_pytorch/Market-1501-v15.09.15/pytorch/query

### ISSUE THREAD

**Issue by MetehanYasar11** [layumi/Person_reID_baseline_pytorch#375]
After I train the model with tutorial dataset, I tried to run this command below in colab;

!python test.py --gpu_ids 0 --name ft_ResNet50  --batchsize 32 --which_epoch 59 --test_dir /content/drive/MyDrive/Person_reID_baseline_pytorch/Market-1501-v15.09.15/pytorch

and I get this error;

This is not an error. If you want to use low precision, i.e., fp16, please install the apex with cuda support (https://github.com/NVIDIA/apex) and update pytorch to 1.0
We use the scale: 1
Traceback (most recent call last):
  File "/content/drive/MyDrive/Person_reID_baseline_pytorch/test.py", line 146, in <module>
    image_datasets = {x: datasets.ImageFolder( os.path.join(data_dir,x) ,data_transforms) for x in ['gallery','query']}
  File "/content/drive/MyDrive/Person_reID_baseline_pytorch/test.py", line 146, in <dictcomp>
    image_datasets = {x: datasets.ImageFolder( os.path.join(data_dir,x) ,data_transforms) for x in ['gallery','query']}
  File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/folder.py", line 144, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/folder.py", line 218, in find_classes
    return find_classes(directory)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/folder.py", line 42, in find_classes
    raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
FileNotFoundError: Couldn't find any class folder in /content/drive/MyDrive/Person_reID_baseline_pytorch/Market-1501-v15.09.15/pytorch/query.

When I look into /content/drive/MyDrive/Person_reID_baseline_pytorch/Market-1501-v15.09.15/pytorch/query, there is nothing...

**Comment by MetehanYasar11** [comment]
> Hi @MetehanYasar11 Do you download the dataset? and successfully use prepare.py to make sub-folders?

Yes, I have downloaded dataset and and executed succesfully prepare.py and train.py
