### ISSUE TITLE
when i use train.py ,it can't run normal!!!

### ISSUE THREAD

**Issue by 695874419** [layumi/Person_reID_baseline_pytorch#55]
wty@z:~/soft_wty/Person_reID_baseline_pytorch-master$ python3 train.py --gpu_ids 0 --name ft_ResNet50 --train_all --batchsize 32  --data_dir /home/wty/soft_wty/dataset/market1501  --erasing_p 0.5
Downloading: "https://download.pytorch.org/models/densenet121-a639ec97.pth" to /home/wty/.torch/models/densenet121-a639ec97.pth
Traceback (most recent call last):
  File "/home/wty/soft_wty/local_install/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/wty/soft_wty/local_install/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/wty/soft_wty/local_install/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/wty/soft_wty/local_install/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/wty/soft_wty/local_install/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/wty/soft_wty/local_install/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/wty/soft_wty/local_install/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/home/wty/soft_wty/local_install/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/home/wty/soft_wty/local_install/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/home/wty/soft_wty/local_install/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/home/wty/soft_wty/local_install/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from model import ft_net, ft_net_dense, PCB
  File "/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py", line 200, in <module>
    net = ft_net_dense(751)
  File "/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py", line 83, in __init__
    model_ft = models.densenet121(pretrained=True)
  File "/home/wty/soft_wty/local_install/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/models/densenet.py", line 35, in densenet121
  File "/home/wty/soft_wty/local_install/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 65, in load_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/wty/soft_wty/local_install/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 70, in _download_url_to_file
    u = urlopen(url)
  File "/home/wty/soft_wty/local_install/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/wty/soft_wty/local_install/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/wty/soft_wty/local_install/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/wty/soft_wty/local_install/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/wty/soft_wty/local_install/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/wty/soft_wty/local_install/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>

pip3 list show:
cycler (0.10.0)
kiwisolver (1.0.1)
matplotlib (2.2.2)
numpy (1.15.0)
Pillow (5.2.0)
pip (9.0.3)
pyparsing (2.2.0)
python-dateutil (2.7.3)
pytz (2018.5)
PyYAML (3.13)
setuptools (39.0.1)
six (1.11.0)
torch (0.4.0)
torchvision (0.2.1)
tqdm (3.7.0)

python3 -V show:
Python 3.6.5

**Comment by layumi** [comment]
Hi @695874419 ,
It seems to be a network connection problem. Could you check your network?

**Comment by dyh127** [comment]
Hi @695874419,
It seems like a network connection problem when you download the pretrainmodel from the url(https://download.pytorch.org/models/densenet121-a639ec97.pth) which need outer net.
So I recommend you check your network or to download the pretrainmodel first then to train.You can download the pretrainmodel from the url to ~/.torch/model and then run the train code,It may solve the problem

**Comment by 695874419** [comment]
thank dyh127 i hava already resolve this problem,the Training complete successful,but when i run test cmd:
python3 test.py --gpu_ids 0 --name ft_ResNet50 --test_dir /home/wty/soft_wty/dataset/market1501/pytorch   --which_epoch 59

it show:
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

i change the epoch,there are another problem:
python3 test.py --gpu_ids 0 --name ft_ResNet50 --test_dir /home/wty/soft_wty/dataset/market1501/pytorch   --which_epoch 20

problem:
/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py:14: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(m.weight.data, a=0, mode='fan_out')
/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py:15: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py:17: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, 1.0, 0.02)
/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py:18: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py:23: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, std=0.001)
/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py:24: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
net output size:
torch.Size([8, 751])
-------test-----------
Traceback (most recent call last):
  File "test.py", line 179, in <module>
    model = load_network(model_structure)
  File "test.py", line 93, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/home/wty/soft_wty/local_install/lib/python3.6/site-packages/torch/serialization.py", line 301, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './model/ft_ResNet50/net_20.pth'

where can i get the 'ft_ResNet50/net_20.pth' file?

**Comment by 695874419** [comment]
thank dyh127 i hava already resolve this problem,the Training complete successful,but when i run test cmd:
python3 test.py --gpu_ids 0 --name ft_ResNet50 --test_dir /home/wty/soft_wty/dataset/market1501/pytorch   --which_epoch 59

it show:
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

i change the epoch,there are another problem:
python3 test.py --gpu_ids 0 --name ft_ResNet50 --test_dir /home/wty/soft_wty/dataset/market1501/pytorch   --which_epoch 20

problem:
/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py:14: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(m.weight.data, a=0, mode='fan_out')
/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py:15: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py:17: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, 1.0, 0.02)
/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py:18: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py:23: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, std=0.001)
/home/software_mount/wty/Person_reID_baseline_pytorch-master/model.py:24: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
net output size:
torch.Size([8, 751])
-------test-----------
Traceback (most recent call last):
  File "test.py", line 179, in <module>
    model = load_network(model_structure)
  File "test.py", line 93, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/home/wty/soft_wty/local_install/lib/python3.6/site-packages/torch/serialization.py", line 301, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './model/ft_ResNet50/net_20.pth'

where can i get the 'ft_ResNet50/net_20.pth' file?

**Comment by layumi** [comment]
1. I store the model file every 10 epochs. So you may load 9th/19th/29th/39th/49th/59th model. 
2.  The first error is caused by the limitation of the GPU memory. I suggest you to add `--batchsize 32` to run. If the error still exists, you may try smaller batchsize.

**Comment by 695874419** [comment]
thank you very much，According to your method, I solved these problems successfully .
