### ISSUE TITLE
i run test.py when i used pretrained model ft_Restnet50,error occured

### ISSUE THREAD

**Issue by zgctmac** [layumi/Person_reID_baseline_pytorch#61]
Traceback (most recent call last):
  File "test.py", line 179, in <module>
    model = load_network(model_structure)
  File "test.py", line 93, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/root/anaconda3/envs/zgc/lib/python2.7/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ft_net:
	Missing key(s) in state_dict: "model.fc.bias", "model.fc.weight", "classifier.add_block.0.bias", "classifier.add_block.0.weight", "classifier.add_block.1.running_var", "classifier.add_block.1.bias", "classifier.add_block.1.weight", "classifier.add_block.1.running_mean", "classifier.classifier.0.bias", "classifier.classifier.0.weight".
	Unexpected key(s) in state_dict: "model.fc.0.weight", "model.fc.0.bias", "model.fc.1.weight", "model.fc.1.bias", "model.fc.1.running_mean", "model.fc.1.running_var", "classifier.0.weight", "classifier.0.bias".

**Comment by jj8401** [comment]
https://github.com/layumi/Person_reID_baseline_pytorch/issues/37
