### ISSUE TITLE
about train.py :module name can\'t contain "."'

### ISSUE THREAD

**Issue by Small93** [layumi/Person_reID_baseline_pytorch#65]
i use  torchvision=0.2.0 and run 'python train.py --gpu_ids 0 --name ft_ResNet50 --train_all --batchsize 32  --data_dir /home/data/project/Person_reID/Market-1501-v15.09.15/pytorch'. i can't find the error,Looking forward to your help。
raceback (most recent call last):
  File "train.py", line 20, in <module>
    from model import ft_net, ft_net_dense, PCB
  File "/home/data/project/Person_reID/model.py", line 200, in <module>
    net = ft_net_dense(751)
  File "/home/data/project/Person_reID/model.py", line 83, in __init__
    model_ft = models.densenet121(pretrained=True)
  File "/home/software/anaconda/envs/ReID/lib/python3.6/site-packages/torchvision/models/densenet.py", line 26, in densenet121
    **kwargs)
  File "/home/software/anaconda/envs/ReID/lib/python3.6/site-packages/torchvision/models/densenet.py", line 142, in __init__
    bn_size=bn_size, growth_rate=growth_rate, drop_rate=drop_rate)
  File "/home/software/anaconda/envs/ReID/lib/python3.6/site-packages/torchvision/models/densenet.py", line 98, in __init__
    layer = _DenseLayer(num_input_features + i * growth_rate, growth_rate, bn_size, drop_rate)
  File "/home/software/anaconda/envs/ReID/lib/python3.6/site-packages/torchvision/models/densenet.py", line 77, in __init__
    self.add_module('norm.1', nn.BatchNorm2d(num_input_features)),#change norm.1
  File "/home/software/anaconda/envs/ReID/lib/python3.6/site-packages/torch/nn/modules/module.py", line 169, in add_module
    raise KeyError("module name can't contain \".\"")
KeyError: 'module name can\'t contain "."'
(ReID) root@ubnutu:/home/data/project/Person_reID# python train.py --gpu_ids 0 --name ft_ResNet121 --train_all --batchsize 32  --data_dir /home/data/project/Person_reID/Market-1501-v15.09.15/pytorch
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from model import ft_net, ft_net_dense, PCB
  File "/home/data/project/Person_reID/model.py", line 200, in <module>
    net = ft_net_dense(751)
  File "/home/data/project/Person_reID/model.py", line 83, in __init__
    model_ft = models.densenet121(pretrained=True)
  File "/home/software/anaconda/envs/ReID/lib/python3.6/site-packages/torchvision/models/densenet.py", line 26, in densenet121
    **kwargs)
  File "/home/software/anaconda/envs/ReID/lib/python3.6/site-packages/torchvision/models/densenet.py", line 142, in __init__
    bn_size=bn_size, growth_rate=growth_rate, drop_rate=drop_rate)
  File "/home/software/anaconda/envs/ReID/lib/python3.6/site-packages/torchvision/models/densenet.py", line 98, in __init__
    layer = _DenseLayer(num_input_features + i * growth_rate, growth_rate, bn_size, drop_rate)
  File "/home/software/anaconda/envs/ReID/lib/python3.6/site-packages/torchvision/models/densenet.py", line 77, in __init__
    self.add_module('norm.1', nn.BatchNorm2d(num_input_features)),#change norm.1
  File "/home/software/anaconda/envs/ReID/lib/python3.6/site-packages/torch/nn/modules/module.py", line 169, in add_module
    raise KeyError("module name can't contain \".\"")

**Comment by layumi** [comment]
Hi @Small93 
You may check the issue in pytorch https://github.com/pytorch/pytorch/issues/6941.
It is caused by the DenseNet in torchvision.
To solve it, please reinstall the torchvision from the source.

**Comment by Small93** [comment]
@layumi it works very well, thanks.
