### ISSUE TITLE
Is this the problem of pytorch-vision?

### ISSUE THREAD

**Issue by ngunauj** [layumi/Person_reID_baseline_pytorch#82]
when i train the momel use `python train.py --gpu_ids 0 --name ft_ResNet50 --train_all --batchsize 32  --data_dir your_data_path`
```
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from model import ft_net, ft_net_dense, PCB
  File "/home/guan/pytorch/reID/Person_reID_baseline_pytorch/model.py", line 200, in <module>
    net = ft_net_dense(751)
  File "/home/guan/pytorch/reID/Person_reID_baseline_pytorch/model.py", line 83, in __init__
    model_ft = models.densenet121(pretrained=True)
  File "/home/guan/anaconda3/lib/python3.6/site-packages/torchvision/models/densenet.py", line 25, in densenet121
    model = DenseNet(num_init_features=64, growth_rate=32, block_config=(6, 12, 24, 16))
  File "/home/guan/anaconda3/lib/python3.6/site-packages/torchvision/models/densenet.py", line 138, in __init__
    bn_size=bn_size, growth_rate=growth_rate, drop_rate=drop_rate)
  File "/home/guan/anaconda3/lib/python3.6/site-packages/torchvision/models/densenet.py", line 94, in __init__
    layer = _DenseLayer(num_input_features + i * growth_rate, growth_rate, bn_size, drop_rate)
  File "/home/guan/anaconda3/lib/python3.6/site-packages/torchvision/models/densenet.py", line 73, in __init__
    self.add_module('norm.1', nn.BatchNorm2d(num_input_features)),
  File "/home/guan/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 169, in add_module
    raise KeyError("module name can't contain \".\"")
KeyError: 'module name can\'t contain "."'

```

**Comment by layumi** [comment]
You may check the issue here.
https://github.com/pytorch/pytorch/issues/6941

**Comment by ngunauj** [comment]
@layumi  thank you!
i have solve the problem for there are two version torchvision(0.1.8 and 0.2.1) in my conda env. 
after `pip uninstall torchvision`, it works
