### ISSUE TITLE
  train ft_net 时RuntimeError，再请教一下为什么数据预处理这块运行了两遍

### ISSUE THREAD

**Issue by yaodonggggggg** [layumi/Person_reID_baseline_pytorch#89]
我在train.py中加了几个print
if opt.erasing_p>0:
    transform_train_list = transform_train_list +  [RandomErasing(probability = opt.erasing_p, mean=[0.0, 0.0, 0.0])]
if opt.color_jitter:
    transform_train_list = [transforms.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1, hue=0)] + transform_train_list
**print('开始预处理')** 
print(transform_train_list)
data_transforms = {
    'train': transforms.Compose( transform_train_list ),
    'val': transforms.Compose(transform_val_list),
}
**print('预处理结束')**
train_all = ''
if opt.train_all:
     train_all = '_all'

image_datasets = {}
image_datasets['train'] = datasets.ImageFolder(os.path.join(data_dir, 'train' + train_all),
                                          data_transforms['train'])
image_datasets['val'] = datasets.ImageFolder(os.path.join(data_dir, 'val'),
                                          data_transforms['val'])

dataloaders = {x: torch.utils.data.DataLoader(image_datasets[x], batch_size=opt.batchsize,
                                             shuffle=True, num_workers=8) # 8 workers may work faster
              for x in ['train', 'val']}
dataset_sizes = {x: len(image_datasets[x]) for x in ['train', 'val']}
class_names = image_datasets['train'].classes
**print('train和val分配')**
use_gpu = torch.cuda.is_available()
**print('使用gpu')**
since = time.time()

inputs, classes = next(iter(dataloaders['train']))
print(time.time()-since)

**在cmd中运行时**

D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master>python train.py
D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master\model.py:14: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(m.weight.data, a=0, mode='fan_out')
D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master\model.py:15: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master\model.py:17: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, 1.0, 0.02)
D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master\model.py:18: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master\model.py:23: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, std=0.001)
D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master\model.py:24: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
ft_net(
  (model): ResNet(
  )
)
net output size:
torch.Size([8, 751])
0
开始预处理
[Resize(size=(288, 144), interpolation=PIL.Image.BICUBIC), RandomCrop(size=(256, 128), padding=0), RandomHorizontalFlip(p=0.5), ToTensor(), Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])]
预处理结束
train和val分配
使用gpu
D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master\model.py:14: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(m.weight.data, a=0, mode='fan_out')
D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master\model.py:15: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master\model.py:17: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, 1.0, 0.02)
D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master\model.py:18: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master\model.py:23: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, std=0.001)
D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master\model.py:24: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
ft_net(
  (model): ResNet(
  )
)
net output size:
torch.Size([8, 751])
0
开始预处理
[Resize(size=(288, 144), interpolation=PIL.Image.BICUBIC), RandomCrop(size=(256, 128), padding=0), RandomHorizontalFlip(p=0.5), ToTensor(), Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])]
预处理结束
train和val分配
使用gpu
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    Traceback (most recent call last):
exitcode = _main(fd)  File "train.py", line 124, in <module>

      File "D:\anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
inputs, classes = next(iter(dataloaders['train']))
prepare(preparation_data)  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__

      File "D:\anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
return _DataLoaderIter(self)
_fixup_main_from_path(data['init_main_from_path'])  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__

      File "D:\anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
w.start()
  File "D:\anaconda3\lib\multiprocessing\process.py", line 105, in start
        run_name="__mp_main__")self._popen = self._Popen(self)

  File "D:\anaconda3\lib\runpy.py", line 263, in run_path
  File "D:\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
        pkg_name=pkg_name, script_name=fname)return _default_context.get_context().Process._Popen(process_obj)

  File "D:\anaconda3\lib\runpy.py", line 96, in _run_module_code
  File "D:\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
        mod_name, mod_spec, pkg_name, script_name)return Popen(process_obj)

  File "D:\anaconda3\lib\runpy.py", line 85, in _run_code
  File "D:\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
        exec(code, run_globals)reduction.dump(process_obj, to_child)

  File "D:\python_workspace\Person_reID_baseline_pytorch-master\Person_reID_baseline_pytorch-master\train.py", line 124, in <module>
  File "D:\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
        inputs, classes = next(iter(dataloaders['train']))ForkingPickler(file, protocol).dump(obj)

  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
BrokenPipeError    : return _DataLoaderIter(self)[Errno 32] Broken pipe

  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    w.start()
  File "D:\anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
感觉是第125行inputs, classes = next(iter(dataloaders['train']))出的错
请问为什么模型还有数据预处理部分会重复运行两次，而且# set gpu ids这一块也运行到了？
请问这个RuntimeError:该怎么处理？在125行前面添加了
def run():
    torch.multiprocessing.freeze_support()
    print('loop')

if __name__ == '__main__':
    run()
也没有用

**Comment by layumi** [comment]
Hi @yaodonggggggg 
It seems to be a bug with Windows pytorch.
You may check some windows doc:
https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection
